#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

if [[ "$(id -u)" -eq 0 ]]; then
  echo "[launch_validation_api] Refusing to run as root. Run as a non-root user." >&2
  exit 1
fi

NETWORK=""
PROCESS_NAME=""
ENV_OUT=""
VENV_DIR=""
HTTP_HOST="127.0.0.1"
HTTP_PORT="8888"
GCP_CREDS_FILE=""
AUTO_INSTALL_PM2="0"
PM2_NAMESPACE="${PM2_NAMESPACE:-}"


usage() {
  cat <<'EOF'
Launch the sandbox Validation API under PM2.

Usage:
  bash scripts/validator/process/launch_validation_api.sh --network NETWORK --gcp-creds-file /path/key.json [options]

Required (one of):
  --gcp-creds-file PATH    Service account JSON key for token minting
  OR set GOOGLE_OAUTH_ACCESS_TOKEN in the environment

Options:
  --network NAME           Network alias used only for defaults (local|test|finney)
  --process-name NAME      Default: alphacore-validation-api
  --pm2-namespace NAME     Default: alphacore (or env PM2_NAMESPACE)
  --env-out PATH           Default: env/<network>/validation-api.env
  --venv-dir PATH          Default: <repo>/.venv-validation-api
  --bind-host HOST         Default: 127.0.0.1
  --port PORT              Default: 8888
  --auto-install-pm2       Install pm2 if missing (uses install_pm2.sh)
  --help|-h                Show this help

Notes:
  One-time host provisioning (Firecracker/kernel/rootfs/TAP/DNS/proxy):
    sudo bash modules/evaluation/validation/sandbox/setup.sh
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --network) NETWORK="$2"; shift 2 ;;
    --process-name) PROCESS_NAME="$2"; shift 2 ;;
    --env-out) ENV_OUT="$2"; shift 2 ;;
    --venv-dir) VENV_DIR="$2"; shift 2 ;;
    --bind-host) HTTP_HOST="$2"; shift 2 ;;
    --port) HTTP_PORT="$2"; shift 2 ;;
    --gcp-creds-file) GCP_CREDS_FILE="$2"; shift 2 ;;
    --auto-install-pm2) AUTO_INSTALL_PM2="1"; shift ;;
    --pm2-namespace) PM2_NAMESPACE="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *)
      echo "[launch_validation_api] Unknown option: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${NETWORK:-}" ]]; then
  echo "[launch_validation_api] Missing required: --network (used for default paths/names)" >&2
  usage
  exit 1
fi

if [[ -z "$GCP_CREDS_FILE" && -z "${GOOGLE_OAUTH_ACCESS_TOKEN:-}" ]]; then
  echo "[launch_validation_api] Missing auth: pass --gcp-creds-file or set GOOGLE_OAUTH_ACCESS_TOKEN" >&2
  exit 1
fi
if [[ -n "$GCP_CREDS_FILE" && ! -f "$GCP_CREDS_FILE" ]]; then
  echo "[launch_validation_api] --gcp-creds-file not found: $GCP_CREDS_FILE" >&2
  exit 1
fi

if [[ -z "$VENV_DIR" ]]; then
  VENV_DIR="$REPO_ROOT/.venv-validation-api"
fi
if [[ -z "$PROCESS_NAME" ]]; then
  PROCESS_NAME="alphacore-validation-api"
fi
if [[ -z "${PM2_NAMESPACE:-}" ]]; then
  PM2_NAMESPACE="alphacore"
fi
if [[ -z "$ENV_OUT" ]]; then
  ENV_OUT="$REPO_ROOT/env/${NETWORK}/validation-api.env"
fi
mkdir -p "$(dirname "$ENV_OUT")"

if [[ ! -e /dev/kvm ]]; then
  echo "[launch_validation_api] WARNING: /dev/kvm not found; Firecracker jobs will not run." >&2
  echo "[launch_validation_api] Run the one-time setup: sudo bash $REPO_ROOT/modules/evaluation/validation/sandbox/setup.sh" >&2
fi

cat >"$ENV_OUT" <<ENVFILE
# Auto-generated by scripts/validator/process/launch_validation_api.sh

ALPHACORE_VALIDATION_HTTP_HOST="${HTTP_HOST}"
ALPHACORE_VALIDATION_HTTP_PORT="${HTTP_PORT}"

# Sandbox runner execution
ALPHACORE_SANDBOX_PYTHON="/usr/bin/python3"
ALPHACORE_SANDBOX_USE_SUDO="true"

# Optional: per-job logs/submissions
ALPHACORE_VALIDATION_LOG_DIR="$REPO_ROOT/logs/validation"
ALPHACORE_VALIDATION_ACTIVE_LOG_DIR="$REPO_ROOT/logs/validation/active"
ALPHACORE_VALIDATION_SUBMISSIONS_DIR="$REPO_ROOT/logs/validation/submissions"
ENVFILE
chmod 600 "$ENV_OUT" || true

if [[ -n "$GCP_CREDS_FILE" ]]; then
  printf 'ALPHACORE_GCP_CREDS_FILE="%s"\n' "$GCP_CREDS_FILE" >>"$ENV_OUT"
fi

VALIDATION_SETUP="$REPO_ROOT/modules/evaluation/validation/sandbox/setup_validation_api_pm2.sh"
if [[ ! -x "$VALIDATION_SETUP" ]]; then
  echo "[launch_validation_api] Validation API setup script not found/executable: $VALIDATION_SETUP" >&2
  exit 1
fi

PROCESS_NAME="$PROCESS_NAME" \
PM2_NAMESPACE="$PM2_NAMESPACE" \
VENV_DIR="$VENV_DIR" \
ENV_FILE="$ENV_OUT" \
ALPHACORE_VALIDATION_HTTP_HOST="$HTTP_HOST" \
ALPHACORE_VALIDATION_HTTP_PORT="$HTTP_PORT" \
ALPHACORE_GCP_CREDS_FILE="${GCP_CREDS_FILE:-${ALPHACORE_GCP_CREDS_FILE:-}}" \
AUTO_INSTALL_PM2="$AUTO_INSTALL_PM2" \
bash "$VALIDATION_SETUP"

echo "[launch_validation_api] Validation API started. View logs with: pm2 logs $PROCESS_NAME"
