#!/bin/bash
# setup.sh - Setup Python environment for AlphaCore validator
# Based on Autoppia pattern: venv + dependencies only, no system packages

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
VENV_DIR="${VENV_DIR:-$REPO_ROOT/venv}"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"
WALLET_NAME=""
WALLET_HOTKEY=""
NETUID="${ALPHACORE_NETUID:-${AC_NETUID:-1}}"
NETWORK="${ALPHACORE_NETWORK:-local}"
CHAIN_ENDPOINT="${ALPHACORE_CHAIN_ENDPOINT:-ws://127.0.0.1:9944}"

handle_error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
  exit 1
}

success_msg() {
  echo -e "${GREEN}[SUCCESS]${NC} $1"
}

info_msg() {
  echo -e "${BLUE}[INFO]${NC} $1"
}

warn_msg() {
  echo -e "${YELLOW}[WARN]${NC} $1"
}

print_header() {
  echo ""
  echo -e "${GREEN}╔════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║ $1${NC}"
  echo -e "${GREEN}╚════════════════════════════════════╝${NC}"
  echo ""
}

print_usage() {
  cat << EOF
Usage: bash setup.sh [OPTIONS]

Setup Python environment for AlphaCore validator.

Options:
  --wallet NAME         Wallet name (coldkey)
  --hotkey NAME         Hotkey name
  --netuid NUM          Subnet ID (default: 1)
  --env PROFILE         Environment profile: local|testing|production (default: local)
  --help                Show this help message

Example:
  bash setup.sh --wallet validator-a --hotkey validator-a --netuid 1

EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      --wallet)
        WALLET_NAME="$2"
        shift 2
        ;;
      --hotkey)
        WALLET_HOTKEY="$2"
        shift 2
        ;;
      --netuid)
        NETUID="$2"
        shift 2
        ;;
      --env)
        ENV_PROFILE="$2"
        shift 2
        ;;
      --help)
        print_usage
        exit 0
        ;;
      *)
        echo "Unknown option: $1"
        print_usage
        exit 1
        ;;
    esac
  done
}

check_prerequisites() {
  print_header "Step 1: Checking Prerequisites"
  
  if ! command -v python3.11 &> /dev/null; then
    handle_error "Python 3.11 not found. Run install_dependencies.sh first."
  fi
  success_msg "Python 3.11 found: $(python3.11 --version)"
  
  if ! command -v docker &> /dev/null; then
    handle_error "Docker not found. Run install_dependencies.sh first."
  fi
  success_msg "Docker found: $(docker --version)"
  
  if ! command -v git &> /dev/null; then
    handle_error "Git not found. Run install_dependencies.sh first."
  fi
  success_msg "Git found: $(git --version)"
}

get_wallet_info() {
  print_header "Step 2: Validator Identity"
  
  if [[ -z "$WALLET_NAME" ]]; then
    echo -e "${YELLOW}Enter your validator wallet name (coldkey):${NC}"
    echo "  (This must match your created Bittensor wallet)"
    read -p "  Wallet name: " WALLET_NAME
  fi
  
  if [[ -z "$WALLET_HOTKEY" ]]; then
    echo -e "${YELLOW}Enter your validator hotkey name:${NC}"
    echo "  (This must match your created Bittensor hotkey)"
    read -p "  Hotkey name: " WALLET_HOTKEY
  fi
  
  if [[ -z "$WALLET_NAME" || -z "$WALLET_HOTKEY" ]]; then
    handle_error "Wallet name and hotkey are required"
  fi
  
  success_msg "Wallet: $WALLET_NAME"
  success_msg "Hotkey: $WALLET_HOTKEY"
}

setup_venv() {
  print_header "Step 3: Python Virtual Environment"
  
  if [[ ! -d "$VENV_DIR" ]]; then
    info_msg "Creating virtual environment at $VENV_DIR..."
    python3.11 -m venv "$VENV_DIR" \
      || handle_error "Failed to create virtualenv"
    success_msg "Virtual environment created"
  else
    info_msg "Virtual environment already exists at $VENV_DIR"
  fi
  
  info_msg "Activating virtual environment..."
  source "$VENV_DIR/bin/activate" \
    || handle_error "Failed to activate virtualenv"
  success_msg "Virtual environment activated"
  
  info_msg "Upgrading pip, setuptools, wheel..."
  python -m pip install --upgrade pip setuptools wheel > /dev/null 2>&1 \
    || handle_error "Failed to upgrade pip"
  success_msg "pip upgraded to $(pip --version)"
}

create_env_file() {
  print_header "Step 4: Environment Configuration"
  
  if [[ -f "$ENV_FILE" ]]; then
    warn_msg "Environment file exists: $ENV_FILE"
    read -p "  Overwrite? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      info_msg "Keeping existing .env"
      return
    fi
  fi
  
  info_msg "Creating configuration file: $ENV_FILE"
  
  cat > "$ENV_FILE" << ENVFILE
# AlphaCore Validator Configuration
# Generated by setup.sh on $(date)

# Environment profile
ALPHACORE_ENV=${ENV_PROFILE:-local}

# Validator Identity (REQUIRED)
ALPHACORE_WALLET_NAME="$WALLET_NAME"
ALPHACORE_WALLET_HOTKEY="$WALLET_HOTKEY"

# Subnet Configuration
ALPHACORE_NETUID=$NETUID
ALPHACORE_NETWORK=$NETWORK
ALPHACORE_CHAIN_ENDPOINT=$CHAIN_ENDPOINT
BT_NETWORK=$NETWORK

# Validator Timing
ALPHACORE_ROUND_CADENCE_SECONDS=60  # seconds
ALPHACORE_TASK_TIMEOUT_SECONDS=30   # seconds

# Task Generation
ALPHACORE_PRE_GENERATED_TASKS=5
ALPHACORE_TASKS_PER_ROUND=1

# Burn Mechanism
ALPHACORE_BURN_UID=5
ALPHACORE_BURN_AMOUNT_PERCENTAGE=0.925

# Validation API (external scoring service)
ALPHACORE_VALIDATION_API_ENABLED=true
ALPHACORE_VALIDATION_API_ENDPOINT="http://127.0.0.1:8001"
ALPHACORE_VALIDATION_API_TIMEOUT=300  # seconds
ALPHACORE_VALIDATION_API_RETRIES=2

# LLM Settings (optional - set your OpenAI key if using)
# ALPHACORE_OPENAI_API_KEY="sk-..."
# ALPHACORE_LLM_MODEL="gpt-4o-mini"
# ALPHACORE_ENABLE_LLM=true

ENVFILE
  
  success_msg "Configuration created at $ENV_FILE"
  info_msg "Review and edit as needed"
}

install_dependencies() {
  print_header "Step 5: Installing Python Dependencies"
  
  cd "$REPO_ROOT"
  
  if [[ -f "requirements.txt" ]]; then
    info_msg "Installing from requirements.txt..."
    pip install -r requirements.txt > /dev/null 2>&1 \
      || handle_error "Failed to install requirements"
    success_msg "Requirements installed"
  elif [[ -f "modules/requirements.txt" ]]; then
    info_msg "Installing from modules/requirements.txt..."
    pip install -r modules/requirements.txt > /dev/null 2>&1 \
      || handle_error "Failed to install requirements"
    success_msg "Requirements installed"
  else
    warn_msg "requirements.txt not found, installing minimal dependencies..."
    pip install bittensor==10.0.0 > /dev/null 2>&1 \
      || handle_error "Failed to install bittensor"
    success_msg "Bittensor installed"
  fi
  
  # Install alphacore in development mode
  if [[ -f "setup.py" ]]; then
    info_msg "Installing alphacore in development mode..."
    pip install -e . > /dev/null 2>&1 \
      || handle_error "Failed to install alphacore"
    success_msg "AlphaCore installed in development mode"
  fi
}

check_wallet_exists() {
  print_header "Step 6: Checking Wallet"
  
  info_msg "Checking if wallet exists: $WALLET_NAME (hotkey: $WALLET_HOTKEY)"
  
  if command -v btcli &> /dev/null; then
    if btcli wallet list 2>/dev/null | grep -q "$WALLET_NAME"; then
      success_msg "Wallet found!"
      return 0
    fi
  fi
  
  warn_msg "Could not verify wallet exists"
  warn_msg "Ensure you have created the wallet before running validator:"
  echo "  btcli wallet create --wallet.name $WALLET_NAME"
  echo "  btcli wallet create --wallet.name $WALLET_NAME --wallet.hotkey $WALLET_HOTKEY"
  echo ""
  read -p "  Continue anyway? [y/N] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
}

main() {
  parse_args "$@"
  
  echo ""
  echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║ AlphaCore Validator - Python Setup     ║${NC}"
  echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
  echo ""
  
  check_prerequisites
  get_wallet_info
  setup_venv
  create_env_file
  install_dependencies
  check_wallet_exists
  
  print_header "Setup Complete!"
  echo ""
  echo "Environment configured successfully!"
  echo ""
  echo "Next steps:"
  echo "  1. Review configuration: $ENV_FILE"
  echo "  2. Ensure wallet is funded with TAO"
  echo "  3. Register validator: bash scripts/validator/main/register.sh"
  echo "  4. Start validator: python neurons/validator.py"
  echo ""
  echo "Or use start_validator.py for dual services (validator + task gen API):"
  echo "  python scripts/start_validator.py"
  echo ""
}

main "$@"
